[package]
name = "rsteal"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]

[target.'cfg(unix)'.dependencies]
nmdbus = { version = "1.37.3", optional = true }

[features]
default = ["wireless"]
wireless = ["dep:nmbus"]
